plink_binary_files: "/s/project/uk_biobank/processed/clumping/30760/test/binary_fileset"
plink2_binary_files: "/s/project/uk_biobank/processed/Imputation/ukbb_imputation"
threshold: 0.00001
p_val_col: "pval_meta_raw"